---
###
### Install and Configure Remote Workstation
###

- name: "Configure SecureOPS workstation"
  hosts: localhost
  connection: local
  become: yes

  vars:
    ansible_pull_url: "https://github.com/SecureOps/sops-remoteWksDeploy"
    ansible_pull_playbook: "ubuntu.yaml"

  tasks:  
    - fail:
        msg: "not supported" 
      when: ( ansible_distribution not in ['Ubuntu','Debian'] )


    - name: "Add apt repo keys"
      apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - "https://workspaces-client-linux-public-key.s3-us-west-2.amazonaws.com/ADB332E7.asc"
        - "https://dl.google.com/linux/linux_signing_key.pub"

    - name: "Amazon Workspaces Repository"
      apt_repository:
        repo: "deb [arch=amd64] https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu {{ ansible_distribution_release }} main" 
        filename: "amazon-workspaces-clients"
        state: present

    - name: "Amazon Workspaces Repository"
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" 
        filename: "google"
        state: present

    - apt: 
        name:
          - "python-minimal"
          - "git"
          - "ansible"
          - "apt-listchanges"
          - "openconnect"
          - "vpnc"
          - "network-manager-openconnect-gnome"
          - "workspacesclient"
          - "google-chrome-stable"
          - "chromium-browser"
        state: "latest"
        update_cache: "yes"

    - import_tasks: "tasks/unattended-upgrades.yaml"
    - import_tasks: "tasks/firewall.yaml"

  post_tasks:

    - cron:
        name:   "Set ansible-pull to run regularly"
        minute:   "*/90"
        job:    "ansible-pull -U {{ ansible_pull_url}} {{ ansible_pull_playbook }} > /var/log/last-ansible-pull.log 2>&1"
  

  handlers:
    - import_tasks: "tasks/handlers.yaml"
